void pointers(int *p, void *ptr);
void listFiles();
void file();
void preprocessor();
void memory();
clock_t zeit();
void sigintHandler(int sig_num);
clock_t vremya();
void ptr_test();
unsigned long long S_to_binary_(const char *s);
void test();
void func_ptr();
void arguments(int args,...);
void pythonScript();
void sandbox();